#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6 7 8 9 X 

# bspc monitor HDMI-1 -d  1 2 3 4 5 6 
# bspc monitor DP-2 -d 7 8 9 X 

# rules
bspc rule -a '*:*:Picture in picture' state=floating 
bspc rule -a '*:*:Picture-in-Picture' state=floating
bspc rule -a eog state=floating follow=on
bspc rule -a "MEGAsync" state=floating follow=on
bspc rule -a feh state=floating follow=on
bspc rule -a menu state=floating follow=on
bspc rule -a "pop-up" state=floating follow=on
bspc rule -a Albert state=floating follow=on



# bspc config top_padding 28
bspc config border_width         3
bspc config window_gap           3
bspc config focused_border_color \#00ff00

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true



# suck
clipmenud &
~/.config/polybar/launch.sh
# dunst &
feh --bg-fill ~/pics/grass.jpg --bg-fill ~/pics/white_mountain.jpg
# feh --bg-fill ~/pics/girl.jpg --bg-fill ~/pics/earth.jpg
# feh --bg-fill ~/pics/g3.jpg --bg-fill ~/pics/g2.png
# feh --bg-fill ~/pics/morn.jpg --bg-fill ~/pics/earth.jpg
albert &
megasync &
picom & 
conky &
conky -c ~/.config/conky/beer.conf &
caffeine &
bspc monitor -f next;bspc monitor -f next 
